### ISSUE TITLE
Eon Ticket and Old Sea Map missing (Emerald PAL)

### ISSUE THREAD

**Issue by gabriele-granata** [suloku/wc-tool#8]
![IMG_20210509_200001671_HDR](https://user-images.githubusercontent.com/83920676/117619926-2a5b1d80-b170-11eb-8147-d6416fa45cbf.jpg)
As the title reads, the Eon Ticket and the Old Sea Map are missing, there are only the Aurora Ticket and Mystic Ticket (USA). I'm playing on an italian original copy of Pokémon Emerald.
This tool is amazing, it has allowed me to get the Aurora and Mystic Ticket that I have always wanted! If it had the Eon Ticket and the Old Sea Map it would be perfect.
Nonetheless, I was able to get two event items on my cartidge when I thought it was impossible. Definitely one great tool, keep up the good work.
**EDIT1**: my bad, when I inserted my Pokémon Ruby cartridge the Eon ticket was shown and ready to be transfered to my cartridge, and after a quick research I discovered that the only way to get an Eon Ticket on Emerald is by linking with a Ruby/Sapphire cartridge that already has an Eon ticket. **As for the Old Sea Map, though, it is indeed missing
** because it seems it was only available for Emerald.
**EDIT2**: I closed this issue because soon after opening it, while I was browsing in Bulbapedia, I discovered that the Old Sea Map was only available in Japan, thus the absence of it in the tool. In the Project Pokemon Forum some users were kind enough to explain to me that the only way you can possibly inject an Eon Ticket and/or an Old Sea Map event in a non-Japanese Emerald cartridge is by using the PC version of this great tool or BlackShark's PKHeX Plugin. As stated by suloku him/herself in the comment section of this issue: _the goal was to provide an easy way for people to get the events that could have been legitimately obtained back in the day (you can still get USA mystic ticket on a PAL cartridge because this was actually possible to be done back in the day)_.

**Comment by suloku** [comment]
Just for the record, the opener of this issue posted a screenshot of the wii/gamecube version of the program.
The the wii/gamecube version (and the nds version) were programmed with LEGAL events in mind. Thus only events that would be legal are allowed to be injected with the apps.
OP was using a non-japanese Emerald cartridge, thus the only events available were aurora ticket and mystick ticket (since eon ticket ad old sea map were only available in japan).

For NON legit events, one should backup the savegame to computer (a wii/gamecube or nds can be used for this purpose), use the PC save editor and restore the savegame.

I repeat, the goal was to provide an easy way for people to get the events that could have been legitimatelly obtained back in the day (you can still get USA mystick ticket on a PAL cartridge because this was actually possoble to be done back in the day).

**Comment by gabriele-granata** [comment]
@suloku I closed this issue because soon after opening it, browsing in Bulbapedia, I discovered that the Old Sea Map was only available in Japan, thus the absence of it in the tool.
I deleted what I wrote (even if the edits can still be seen by everyone) because after discovering that, it didn't really seem like it was an issue in the first place, but rather a request. Though, now that I come to think of it I should have left a second edit message to explain everything and then close the issue.
Anyway, I'm so sorry for the bother. Keep up the great work.
EDIT1: almost forgot, I don't know why exactly but I created an icon.jpg and a meta.xml for this app, so that it has both and icon and a description in the Homebrew Channel. I know it's useless but anyway I could send them to you.
